# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SearchResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, search_id: str=None):  # noqa: E501
        """SearchResponse - a model defined in Swagger

        :param search_id: The search_id of this SearchResponse.  # noqa: E501
        :type search_id: str
        """
        self.swagger_types = {
            'search_id': str
        }

        self.attribute_map = {
            'search_id': 'search_id'
        }
        self._search_id = search_id

    @classmethod
    def from_dict(cls, dikt) -> 'SearchResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The searchResponse of this SearchResponse.  # noqa: E501
        :rtype: SearchResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def search_id(self) -> str:
        """Gets the search_id of this SearchResponse.


        :return: The search_id of this SearchResponse.
        :rtype: str
        """
        return self._search_id

    @search_id.setter
    def search_id(self, search_id: str):
        """Sets the search_id of this SearchResponse.


        :param search_id: The search_id of this SearchResponse.
        :type search_id: str
        """

        self._search_id = search_id
