# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SearchResponseNotFinished(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, finished: bool=None):  # noqa: E501
        """SearchResponseNotFinished - a model defined in Swagger

        :param finished: The finished of this SearchResponseNotFinished.  # noqa: E501
        :type finished: bool
        """
        self.swagger_types = {
            'finished': bool
        }

        self.attribute_map = {
            'finished': 'finished'
        }
        self._finished = finished

    @classmethod
    def from_dict(cls, dikt) -> 'SearchResponseNotFinished':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The searchResponseNotFinished of this SearchResponseNotFinished.  # noqa: E501
        :rtype: SearchResponseNotFinished
        """
        return util.deserialize_model(dikt, cls)

    @property
    def finished(self) -> bool:
        """Gets the finished of this SearchResponseNotFinished.


        :return: The finished of this SearchResponseNotFinished.
        :rtype: bool
        """
        return self._finished

    @finished.setter
    def finished(self, finished: bool):
        """Sets the finished of this SearchResponseNotFinished.


        :param finished: The finished of this SearchResponseNotFinished.
        :type finished: bool
        """

        self._finished = finished
