# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SearchResponseStarted(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, search_id: str=None, finished: bool=None):  # noqa: E501
        """SearchResponseStarted - a model defined in Swagger

        :param search_id: The search_id of this SearchResponseStarted.  # noqa: E501
        :rtype: str
        :param finished: The finished of this SearchResponseStarted.  # noqa: E501
        :type finished: bool
        """
        self.swagger_types = {
            'search_id': str,
            'finished': bool
        }

        self.attribute_map = {
            'search_id': 'search_id',
            'finished': 'finished'
        }
        self._search_id = search_id
        self._finished = finished


    @classmethod
    def from_dict(cls, dikt) -> 'SearchResponseStarted':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The searchResponseStarted of this SearchResponseStarted.  # noqa: E501
        :rtype: SearchResponseStarted
        """
        return util.deserialize_model(dikt, cls)

    @property
    def finished(self) -> bool:
        """Gets the finished of this SearchResponseStarted.


        :return: The finished of this SearchResponseStarted.
        :rtype: bool
        """
        return self._finished
    
    @property
    def search_id(self) -> str:
        """Gets the search_id of this SearchResponseStarted.


        :return: The search_id of this SearchResponseStarted.
        :rtype: str
        """
        return self._search_id

    @finished.setter
    def finished(self, search_id, finished: bool):
        """Sets the finished of this SearchResponseStarted.


        :param search_id: The search_id of this SearchResponseStarted.  # noqa: E501
        :rtype: str
        :param finished: The finished of this SearchResponseStarted.  # noqa: E501
        :type finished: bool
        """
        self._search_id = search_id
        self._finished = finished
